[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-set = "0.5.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
regex = "1.7.0"

# For debug symbols
[profile.release]
debug = 1
